<a href="https://colab.research.google.com/github/saivedant09-gif/EXPLORATORY-DATA-ANALYSIS-2026-27/blob/main/25BDS0226_EXP_3_21_07_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***OPTION-1***

In [14]:
import pandas as pd
import numpy as np

In [15]:

d1A = pd.DataFrame({'ID': list(range(15)),
                    'temp': [15, 22, 35, 11, -2, 28, 19, 32, 25, 14, 8, 30, 21, -5, 17]})
d2A = pd.DataFrame({'ID': list(range(15)),
                    'temp': [12, 29, 31, 5, -8, 26, 18, 34, 22, 16, 3, 27, 23, -1, 13]})
d1B = pd.DataFrame({'ID': list(range(15)),
                    'rain': [12, 45, 0, 8, 110, 23, 56, 0, 15, 88, 4, 12, 67, 34, 0]})
d2B = pd.DataFrame({'ID': list(range(15)),
                    'rain': [0, 14, 78, 92, 5, 0, 43, 11, 29, 85, 0, 19, 54, 3, 72]})

In [16]:

dfTemp = pd.concat([d1A, d2A], ignore_index=True)
dfRain = pd.concat([d1B, d2B], ignore_index=True)
df = pd.concat([dfRain, dfTemp], axis=1)
print("dfTemp (first 5 rows):")
display(dfTemp.head())
print("\ndfRain (first 5 rows):")
display(dfRain.head())
print("\nFinal combined df (first 5 rows):")
display(df.head())

dfTemp (first 5 rows):

   ID  temp
0   0    15
1   1    22
2   2    35
3   3    11
4   4    -2

dfRain (first 5 rows):

   ID  rain
0   0    12
1   1    45
2   2     0
3   3     8
4   4   110

Final combined df (first 5 rows):

   ID  rain  ID  temp
0   0    12   0    15
1   1    45   1    22
2   2     0   2    35
3   3     8   3    11
4   4   110   4    -2

***OPTION-2***

In [17]:
dfTemp = pd.concat([d1A, d2A], ignore_index=True)
dfRain = pd.concat([d1B, d2B], ignore_index=True)
df = dfRain.merge(dfTemp, on='ID', how='inner')
print("Final merged df (first 5 rows):")
display(df.head())

Final merged df (first 5 rows):

   ID  rain  temp
0   0    12    15
1   0    12    12
2   1    45    22
3   1    45    29
4   2     0    35

***OPTION-3***

In [18]:
dfTemp = pd.concat([d1A, d2A], ignore_index=True)
dfRain = pd.concat([d1B, d2B], ignore_index=True)
df = dfRain.merge(dfTemp, on='ID', how='left')
print("Final merged df (first 5 rows):")
display(df.head())

Final merged df (first 5 rows):

   ID  rain  temp
0   0    12    15
1   0    12    12
2   1    45    22
3   1    45    29
4   2     0    35

***OPTION-4***

In [19]:
dfTemp = pd.concat([d1A, d2A], ignore_index=True)
dfRain = pd.concat([d1B, d2B], ignore_index=True)
df = dfRain.merge(dfTemp, on='ID', how='right')
print("Final merged df (first 5 rows):")
display(df.head())

Final merged df (first 5 rows):

   ID  rain  temp
0   0    12    15
1   0     0    15
2   1    45    22
3   1    14    22
4   2     0    35