<a href="https://colab.research.google.com/github/saivedant09-gif/EXPLORATORY-DATA-ANALYSIS-2026-27/blob/main/CLASS_TASK_16_7_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK-1**

In [27]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/employee_salary_500x8_with_missing_values.csv")
df

,Employee_ID,Employee_Name,Department,Designation,Basic_Salary,Bonus,Deduction,Net_Salary
0,EMP0001,Vivaan Joshi,HR,Analyst,36427.0,15344.0,5367.0,46404.0
1,EMP0002,Sneha Johnson,HR,Engineer,98704.0,12885.0,6583.0,105006.0
2,EMP0003,Rohan Kumar,IT,Analyst,98526.0,12937.0,5016.0,106447.0
3,EMP0004,Lucas Choudhary,HR,Analyst,36483.0,21582.0,7186.0,50879.0
4,EMP0005,Priya Kulkarni,Operations,Engineer,38374.0,3438.0,2519.0,39293.0
...,...,...,...,...,...,...,...,...
495,EMP0496,Olivia Roy,IT,Associate,53462.0,19890.0,4628.0,68724.0
496,EMP0497,Kavya Mehta,Sales,Associate,86426.0,5346.0,3926.0,87846.0
497,EMP0498,Diya Brown,Operations,Executive,74237.0,11261.0,8301.0,77197.0
498,EMP0499,Sneha Patel,Finance,Lead,52784.0,19009.0,6698.0,65095.0
499,EMP0500,John Davis,Operations,Manager,77987.0,7821.0,4545.0,81263.0

In [28]:
df.head(5)

,Employee_ID,Employee_Name,Department,Designation,Basic_Salary,Bonus,Deduction,Net_Salary
0,EMP0001,Vivaan Joshi,HR,Analyst,36427.0,15344.0,5367.0,46404.0
1,EMP0002,Sneha Johnson,HR,Engineer,98704.0,12885.0,6583.0,105006.0
2,EMP0003,Rohan Kumar,IT,Analyst,98526.0,12937.0,5016.0,106447.0
3,EMP0004,Lucas Choudhary,HR,Analyst,36483.0,21582.0,7186.0,50879.0
4,EMP0005,Priya Kulkarni,Operations,Engineer,38374.0,3438.0,2519.0,39293.0

In [29]:
df.tail(5)

,Employee_ID,Employee_Name,Department,Designation,Basic_Salary,Bonus,Deduction,Net_Salary
495,EMP0496,Olivia Roy,IT,Associate,53462.0,19890.0,4628.0,68724.0
496,EMP0497,Kavya Mehta,Sales,Associate,86426.0,5346.0,3926.0,87846.0
497,EMP0498,Diya Brown,Operations,Executive,74237.0,11261.0,8301.0,77197.0
498,EMP0499,Sneha Patel,Finance,Lead,52784.0,19009.0,6698.0,65095.0
499,EMP0500,John Davis,Operations,Manager,77987.0,7821.0,4545.0,81263.0

In [30]:
print("TOTAL ROWS=",len(df))
print("TOTAL COLUMNS=",len(df.columns))
print("DATASET SHAPE:",df.shape)

TOTAL ROWS= 500
TOTAL COLUMNS= 8
DATASET SHAPE: (500, 8)

**TASK-2**

In [31]:
print("COLUMNS:\n",df.columns)

COLUMNS:
 Index(['Employee_ID', 'Employee_Name', 'Department', 'Designation',
       'Basic_Salary', 'Bonus', 'Deduction', 'Net_Salary'],
      dtype='object')

In [32]:
df.dtypes

Employee_ID       object
Employee_Name     object
Department        object
Designation       object
Basic_Salary     float64
Bonus            float64
Deduction        float64
Net_Salary       float64
dtype: object

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    500 non-null    object
 1   Employee_Name  500 non-null    object
 2   Department     495 non-null    object
 3   Designation    495 non-null    object
 4   Basic_Salary   495 non-null    float64
 5   Bonus          495 non-null    float64
 6   Deduction      495 non-null    float64
 7   Net_Salary     486 non-null    float64
dtypes: float64(4), object(4)
memory usage: 31.4+ KB

In [34]:
df.describe()

        Basic_Salary         Bonus    Deduction     Net_Salary
count     495.000000    495.000000   495.000000     486.000000
mean    72214.183838  13803.600000  5470.389899   80485.329218
std     27384.666916   6483.650134  2620.916511   28218.277950
min     25465.000000   2011.000000  1053.000000   24741.000000
25%     47432.500000   8351.000000  3151.000000   58499.750000
50%     73845.000000  13846.000000  5367.000000   80975.500000
75%     94944.500000  19223.000000  7730.500000  104896.500000
max    119712.000000  24917.000000  9968.000000  136619.000000

**TASK-3**

In [35]:
print("MISSING VALUES:-\n",df.isnull().sum())

MISSING VALUES:-
 Employee_ID       0
Employee_Name     0
Department        5
Designation       5
Basic_Salary      5
Bonus             5
Deduction         5
Net_Salary       14
dtype: int64

In [36]:
print("PERCENTAGE OF MISSING VALUES:-\n",(df.isnull().sum()/len(df))*100)

PERCENTAGE OF MISSING VALUES:-
 Employee_ID      0.0
Employee_Name    0.0
Department       1.0
Designation      1.0
Basic_Salary     1.0
Bonus            1.0
Deduction        1.0
Net_Salary       2.8
dtype: float64

In [37]:
print("COLUMNS WITH HIGHEST MISSING ENTRIES:-\n", df.isnull().sum().sort_values(ascending=False))

COLUMNS WITH HIGHEST MISSING ENTRIES:-
 Net_Salary       14
Designation       5
Basic_Salary      5
Department        5
Bonus             5
Deduction         5
Employee_ID       0
Employee_Name     0
dtype: int64