<a href="https://colab.research.google.com/github/saivedant09-gif/EXPLORATORY-DATA-ANALYSIS-2026-27/blob/main/EDA_EXP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np

In [56]:
df = pd.read_csv("/content/1000 Sales Records.csv")

In [57]:
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Middle East and North Africa,Azerbaijan,Snacks,Offline,C,4/18/2010,534085166,4/25/2010,6524,152.58,97.44,995431.92,635698.56,359733.36
996,Europe,Georgia,Baby Food,Offline,H,8/1/2011,590768182,9/7/2011,288,255.28,159.42,73520.64,45912.96,27607.68
997,Middle East and North Africa,United Arab Emirates,Vegetables,Online,C,5/12/2011,524363124,6/28/2011,9556,154.06,90.93,1472197.36,868927.08,603270.28
998,Europe,Finland,Household,Offline,L,1/25/2016,289606320,2/14/2016,9801,668.27,502.54,6549714.27,4925394.54,1624319.73
999,Europe,Portugal,Cereal,Offline,C,4/10/2014,811546599,5/8/2014,3528,205.70,117.11,725709.60,413164.08,312545.52

In [58]:
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11/7/2011,185941302,12/8/2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12/9/2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,4/10/2010,161442649,5/12/2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45

In [59]:
df.tail()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
995,Middle East and North Africa,Azerbaijan,Snacks,Offline,C,4/18/2010,534085166,4/25/2010,6524,152.58,97.44,995431.92,635698.56,359733.36
996,Europe,Georgia,Baby Food,Offline,H,8/1/2011,590768182,9/7/2011,288,255.28,159.42,73520.64,45912.96,27607.68
997,Middle East and North Africa,United Arab Emirates,Vegetables,Online,C,5/12/2011,524363124,6/28/2011,9556,154.06,90.93,1472197.36,868927.08,603270.28
998,Europe,Finland,Household,Offline,L,1/25/2016,289606320,2/14/2016,9801,668.27,502.54,6549714.27,4925394.54,1624319.73
999,Europe,Portugal,Cereal,Offline,C,4/10/2014,811546599,5/8/2014,3528,205.70,117.11,725709.60,413164.08,312545.52

In [60]:
df.dtypes

Region             object
Country            object
Item Type          object
Sales Channel      object
Order Priority     object
Order Date         object
Order ID            int64
Ship Date          object
Units Sold          int64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
Total Profit      float64
dtype: object

In [61]:
df_OI = df.groupby(['Order ID'])

In [62]:
df_uc=df.groupby(['Unit Cost'])
df_uc.mean(numeric_only=True)

,Order ID,Units Sold,Unit Price,Total Revenue,Total Cost,Total Profit
Unit Cost,,,,,,
6.92,5.660071e+08,5073.214286,9.33,4.733309e+04,3.510664e+04,12226.446429
31.79,5.752445e+08,4999.059406,47.45,2.372054e+05,1.589201e+05,78285.270297
35.84,5.963542e+08,4845.974359,109.28,5.295681e+05,1.736797e+05,355888.356923
56.67,5.213398e+08,5468.091954,81.73,4.469072e+05,3.098768e+05,137030.384368
90.93,5.409227e+08,4858.515464,154.06,7.485029e+05,4.417848e+05,306718.081237
97.44,5.470611e+08,4818.829268,152.58,7.352570e+05,4.695467e+05,265710.245854
117.11,5.596081e+08,4908.215190,205.70,1.009620e+06,5.748011e+05,434818.783671
159.42,5.065538e+08,5018.597701,255.28,1.281148e+06,8.000648e+05,481082.775632
263.33,5.728326e+08,5680.960000,437.20,2.483716e+06,1.495967e+06,987748.515200
364.69,5.648568e+08,5229.679487,421.89,2.206349e+06,1.907212e+06,299137.666667
502.54,5.367916e+08,4818.077922,668.27,3.219777e+06,2.421277e+06,798500.054026
524.96,5.182806e+08,4994.179775,651.21,3.252260e+06,2.621745e+06,630515.196629

In [63]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [64]:
print("Unique values and counts for categorical columns:")
for column in df.select_dtypes(include='object').columns:
    print(f"\nColumn: {column}")
    print(df[column].value_counts())

Unique values and counts for categorical columns:

Column: Region
Region
Europe                               267
Sub-Saharan Africa                   262
Middle East and North Africa         138
Asia                                 136
Central America and the Caribbean     99
Australia and Oceania                 79
North America                         19
Name: count, dtype: int64

Column: Country
Country
Cuba              11
Zimbabwe          10
Bahrain           10
Czech Republic    10
Malaysia          10
                  ..
Latvia             2
Dominica           2
Cameroon           1
Malta              1
Kosovo             1
Name: count, Length: 185, dtype: int64

Column: Item Type
Item Type
Beverages          101
Vegetables          97
Office Supplies     89
Baby Food           87
Personal Care       87
Snacks              82
Cereal              79
Clothes             78
Meat                78
Household           77
Cosmetics           75
Fruits              70
Name: count, dtype: int64

Column: Sales Channel
Sales Channel
Offline    520
Online     480
Name: count, dtype: int64

Column: Order Priority
Order Priority
L    268
C    262
M    242
H    228
Name: count, dtype: int64

In [65]:
print(f"Number of duplicate rows: {df.duplicated().sum()}")

# If there are duplicates, you might want to remove them
# df.drop_duplicates(inplace=True)
# print(f"Number of rows after removing duplicates: {len(df)}")

Number of duplicate rows: 0

In [66]:
print("Descriptive statistics for numerical columns:")
print(df.describe())

Descriptive statistics for numerical columns:
                          Order Date      Order ID            Ship Date  \
count                           1000  1.000000e+03                 1000
mean   2013-09-19 23:29:45.600000256  5.496813e+08  2013-10-14 23:31:12
min              2010-01-01 00:00:00  1.029280e+08  2010-01-15 00:00:00
25%              2011-11-14 06:00:00  3.280740e+08  2011-12-11 00:00:00
50%              2013-09-24 12:00:00  5.566097e+08  2013-10-12 00:00:00
75%              2015-07-03 00:00:00  7.696945e+08  2015-07-28 06:00:00
max              2017-07-26 00:00:00  9.955298e+08  2017-09-12 00:00:00
std                              NaN  2.571334e+08                  NaN

        Units Sold  Unit Price    Unit Cost  Total Revenue    Total Cost  \
count  1000.000000  1000.00000  1000.000000   1.000000e+03  1.000000e+03
mean   5053.988000   262.10684   184.965110   1.327322e+06  9.361192e+05
min      13.000000     9.33000     6.920000   2.043250e+03  1.416750e+03
25%    2420.250000    81.73000    56.670000   2.811919e+05  1.649319e+05
50%    5184.000000   154.06000    97.440000   7.549392e+05  4.647261e+05
75%    7536.750000   421.89000   263.330000   1.733503e+06  1.141750e+06
max    9998.000000   668.27000   524.960000   6.617210e+06  5.204978e+06
std    2901.375317   216.02106   175.289311   1.486515e+06  1.162571e+06

       Total Profit
count  1.000000e+03
mean   3.912026e+05
min    5.326100e+02
25%    9.837612e+04
50%    2.772260e+05
75%    5.484568e+05
max    1.726181e+06
std    3.836402e+05

In [67]:
print("Unique values and counts for categorical columns:")
for column in df.select_dtypes(include='object').columns:
    print(f"\nColumn: {column}")
    print(df[column].value_counts())

Unique values and counts for categorical columns:

Column: Region
Region
Europe                               267
Sub-Saharan Africa                   262
Middle East and North Africa         138
Asia                                 136
Central America and the Caribbean     99
Australia and Oceania                 79
North America                         19
Name: count, dtype: int64

Column: Country
Country
Cuba              11
Zimbabwe          10
Bahrain           10
Czech Republic    10
Malaysia          10
                  ..
Latvia             2
Dominica           2
Cameroon           1
Malta              1
Kosovo             1
Name: count, Length: 185, dtype: int64

Column: Item Type
Item Type
Beverages          101
Vegetables          97
Office Supplies     89
Baby Food           87
Personal Care       87
Snacks              82
Cereal              79
Clothes             78
Meat                78
Household           77
Cosmetics           75
Fruits              70
Name: count, dtype: int64

Column: Sales Channel
Sales Channel
Offline    520
Online     480
Name: count, dtype: int64

Column: Order Priority
Order Priority
L    268
C    262
M    242
H    228
Name: count, dtype: int64